// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "mp_001",
    name: "Иванов Иван Петрович",
    email: "i.ivanov@mospolytech.ru",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg",
    phone: "+7 (495) 123-45-67",
    position: "Профессор",
    department: "Высшая инженерная школа",
    subjects: ["Высшая математика", "Теория вероятностей"],
    degree: "Доктор технических наук",
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 2,
    teacherId: "mp_002",
    name: "Петрова Анна Сергеевна",
    email: "a.petrova@mospolytech.ru",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg",
    phone: "+7 (495) 123-45-68",
    position: "Доцент",
    department: "Информационные технологии",
    subjects: ["Программирование", "Искусственный интеллект"],
    degree: "Кандидат технических наук",
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 3,
    teacherId: "mp_003",
    name: "Смирнов Михаил Александрович",
    email: "m.smirnov@mospolytech.ru",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg",
    phone: "+7 (495) 123-45-69",
    position: "Старший преподаватель",
    department: "Транспорт",
    subjects: ["Автомобильные двигатели", "Транспортная логистика"],
    degree: "Кандидат технических наук",
    address: "ул. Автозаводская, 16, Москва"
  },
  {
    id: 4,
    teacherId: "mp_004",
    name: "Французов Юрий Викторович",
    email: "y.frantsuzov@mospolytech.ru",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg",
    phone: "+7 (495) 123-45-70",
    position: "Профессор",
    department: "Экономика и управление",
    subjects: ["Эконометрика", "Корпоративные финансы"],
    degree: "Доктор экономических наук",
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 5,
    teacherId: "mp_005",
    name: "Смирнова Екатерина Олеговна",
    email: "e.smirnova@mospolytech.ru",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg",
    phone: "+7 (495) 123-45-71",
    position: "Доцент",
    department: "Дизайн",
    subjects: ["Графический дизайн", "Типографика"],
    degree: "Кандидат искусствоведения",
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 6,
    teacherId: "mp_006",
    name: "Сантьяго Анна Михайловна",
    email: "a.santiago@mospolytech.ru",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg",
    phone: "+7 (495) 123-45-72",
    position: "Профессор",
    department: "Химическая технология",
    subjects: ["Физическая химия", "Нанотехнологии"],
    degree: "Доктор химических наук",
    address: "ул. Прянишникова, 2А, Москва"
  },
  {
    id: 7,
    teacherId: "mp_007",
    name: "Чернов Алексей Дмитриевич",
    email: "a.chernov@mospolytech.ru",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg",
    phone: "+7 (495) 123-45-73",
    position: "Преподаватель",
    department: "Лингвистика",
    subjects: ["Технический английский", "Деловые коммуникации"],
    degree: "Магистр лингвистики",
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 8,
    teacherId: "mp_008",
    name: "Кастро Офелия Романовна",
    email: "o.castro@mospolytech.ru",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg",
    phone: "+7 (495) 123-45-74",
    position: "Доцент",
    department: "Прикладная математика",
    subjects: ["Дискретная математика", "Математическое моделирование"],
    degree: "Кандидат физико-математических наук",
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 9,
    teacherId: "mp_009",
    name: "Бриггс Дмитрий Игоревич",
    email: "d.briggs@mospolytech.ru",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg",
    phone: "+7 (495) 123-45-75",
    position: "Старший преподаватель",
    department: "Урбанистика",
    subjects: ["Городское планирование", "Умные города"],
    degree: "Кандидат архитектуры",
    address: "ул. Автозаводская, 16, Москва"
  },
  {
    id: 10,
    teacherId: "mp_010",
    name: "Глухов Иван Сергеевич",
    email: "i.glukhov@mospolytech.ru",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
    phone: "+7 (495) 123-45-76",
    position: "Доцент",
    department: "Биотехнологии",
    subjects: ["Генная инженерия", "Биоинформатика"],
    degree: "Кандидат биологических наук",
    address: "ул. Прянишникова, 2А, Москва"
  }
];

export const studentsData = [
  {
    id: 1,
    studentId: "mp_2101234",
    name: "Иванов Иван Петрович",
    email: "i.ivanov@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg",
    phone: "+7 (915) 123-45-67",
    faculty: "Информационные технологии",
    group: "211-1234",
    course: 2,
    specialization: "Программная инженерия",
    admissionYear: 2021,
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 2,
    studentId: "mp_2105678",
    name: "Смирнова Анна Дмитриевна",
    email: "a.smirnova@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg",
    phone: "+7 (915) 234-56-78",
    faculty: "Транспорт",
    group: "212-5678",
    course: 2,
    specialization: "Наземные транспортные системы",
    admissionYear: 2021,
    address: "ул. Автозаводская, 16, Москва"
  },
  {
    id: 3,
    studentId: "mp_2209012",
    name: "Кузнецов Михаил Сергеевич",
    email: "m.kuznetsov@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg",
    phone: "+7 (915) 345-67-89",
    faculty: "Химическая технология",
    group: "221-9012",
    course: 1,
    specialization: "Химическая технология",
    admissionYear: 2022,
    address: "ул. Прянишникова, 2А, Москва"
  },
  {
    id: 4,
    studentId: "mp_2103456",
    name: "Францева Юлия Андреевна",
    email: "u.frantseva@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg",
    phone: "+7 (915) 456-78-90",
    faculty: "Дизайн",
    group: "213-3456",
    course: 2,
    specialization: "Графический дизайн",
    admissionYear: 2021,
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 5,
    studentId: "mp_2207890",
    name: "Сидорова Екатерина Олеговна",
    email: "e.sidorova@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg",
    phone: "+7 (915) 567-89-01",
    faculty: "Экономика и управление",
    group: "224-7890",
    course: 1,
    specialization: "Бизнес-информатика",
    admissionYear: 2022,
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 6,
    studentId: "mp_2102345",
    name: "Сантягова Анастасия Викторовна",
    email: "a.santyagova@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg",
    phone: "+7 (915) 678-90-12",
    faculty: "Биотехнологии",
    group: "215-2345",
    course: 2,
    specialization: "Биоинженерия",
    admissionYear: 2021,
    address: "ул. Прянишникова, 2А, Москва"
  },
  {
    id: 7,
    studentId: "mp_2206789",
    name: "Белов Алексей Дмитриевич",
    email: "a.belov@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg",
    phone: "+7 (915) 789-01-23",
    faculty: "Машиностроение",
    group: "226-6789",
    course: 1,
    specialization: "Робототехника",
    admissionYear: 2022,
    address: "ул. Автозаводская, 16, Москва"
  },
  {
    id: 8,
    studentId: "mp_2104567",
    name: "Кастро Офелия Романовна",
    email: "o.kastro@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg",
    phone: "+7 (915) 890-12-34",
    faculty: "Прикладная математика",
    group: "217-4567",
    course: 2,
    specialization: "Прикладная математика",
    admissionYear: 2021,
    address: "ул. Большая Семёновская, 38, Москва"
  },
  {
    id: 9,
    studentId: "mp_2208901",
    name: "Бриггс Дмитрий Игоревич",
    email: "d.briggs@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg",
    phone: "+7 (915) 901-23-45",
    faculty: "Урбанистика",
    group: "228-8901",
    course: 1,
    specialization: "Городское планирование",
    admissionYear: 2022,
    address: "ул. Автозаводская, 16, Москва"
  },
  {
    id: 10,
    studentId: "mp_2105678",
    name: "Гловер Иван Сергеевич",
    email: "i.glover@stud.mospolytech.ru",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
    phone: "+7 (915) 012-34-56",
    faculty: "Энергетика",
    group: "219-5678",
    course: 2,
    specialization: "Возобновляемая энергетика",
    admissionYear: 2021,
    address: "ул. Прянишникова, 2А, Москва"
  }
];

export const parentsData = [
  {
    id: 1,
    name: "Иван Иванов",
    students: ["Сара Бровер"],
    email: "ivan@ivanov.ru",
    phone: "+7 900 123-45-67",
    address: "ул. Ленина, 1, Москва, Россия",
  },
  {
    id: 2,
    name: "Анна Смирнова",
    students: ["Сесилия Бредли"],
    email: "anna@smirnova.ru",
    phone: "+7 900 234-56-78",
    address: "пр. Мира, 12, Санкт-Петербург, Россия",
  },
  {
    id: 3,
    name: "Михаил Кузнецов",
    students: ["Фанни Колдуэлл"],
    email: "mikhail@kuznetsov.ru",
    phone: "+7 900 345-67-89",
    address: "ул. Победы, 8, Екатеринбург, Россия",
  },
  {
    id: 4,
    name: "Юлия Францева",
    students: ["Молли Фицджеральд", "Иван Брайант"],
    email: "yulia@franceva.ru",
    phone: "+7 900 456-78-90",
    address: "ул. Кирова, 15, Казань, Россия",
  },
  {
    id: 5,
    name: "Екатерина Сидорова",
    students: ["Мэйбл Харви"],
    email: "ekaterina@sidorova.ru",
    phone: "+7 900 567-89-01",
    address: "ул. Чехова, 3, Новосибирск, Россия",
  },
  {
    id: 6,
    name: "Анастасия Сантягова",
    students: ["Жоэль Ламберт"],
    email: "anastasia@santiago.ru",
    phone: "+7 900 678-90-12",
    address: "ул. Гоголя, 7, Омск, Россия",
  },
  {
    id: 7,
    name: "Алексей Белов",
    students: ["Карина Такер", "Лилия Андервуд"],
    email: "alexey@belov.ru",
    phone: "+7 900 789-01-23",
    address: "ул. Советская, 22, Пермь, Россия",
  },
  {
    id: 8,
    name: "Офелия Кастро",
    students: ["Александр Блэр"],
    email: "ofeliya@castro.ru",
    phone: "+7 900 890-12-34",
    address: "ул. Школьная, 5, Уфа, Россия",
  },
  {
    id: 9,
    name: "Дмитрий Бриггс",
    students: ["Сьюзан Вебстер", "Мауд Стоун"],
    email: "dmitriy@briggs.ru",
    phone: "+7 900 901-23-45",
    address: "ул. Молодёжная, 9, Тула, Россия",
  },
  {
    id: 10,
    name: "Иван Гловер",
    students: ["Стелла Скотт"],
    email: "ivan@glover.ru",
    phone: "+7 900 012-34-56",
    address: "ул. Парковая, 4, Воронеж, Россия",
  },
];


export const subjectsData = [
  {
    id: 1,
    name: "Информационные технологии",
    teachers: ["Ирина Алексеева", "Владимир Соловьёв"],
  },
  {
    id: 2,
    name: "Инженерный дизайн",
    teachers: ["Мария Романова", "Евгений Лебедев"],
  },
  {
    id: 3,
    name: "Мехатроника и робототехника",
    teachers: ["Александр Кузьмин", "Наталья Демидова"],
  },
  {
    id: 4,
    name: "Транспортные системы",
    teachers: ["Дмитрий Васильев", "Ольга Морозова"],
  },
  {
    id: 5,
    name: "Цифровое производство",
    teachers: ["Кирилл Петров", "Светлана Крылова"],
  },
  {
    id: 6,
    name: "Медиа и коммуникации",
    teachers: ["Анна Белова", "Игорь Зайцев"],
  },
  {
    id: 7,
    name: "Архитектура и урбанистика",
    teachers: ["Татьяна Гончарова", "Михаил Ефимов"],
  },
  {
    id: 8,
    name: "Бизнес и предпринимательство",
    teachers: ["Елена Орлова", "Роман Макаров"],
  },
  {
    id: 9,
    name: "Экологическое проектирование",
    teachers: ["Сергей Тарасов", "Людмила Павлова"],
  },
  {
    id: 10,
    name: "Проектирование пользовательских интерфейсов",
    teachers: ["Николай Смирнов", "Алина Чернова"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "ПК-101",
    capacity: 25,
    grade: 1,
    supervisor: "Ольга Иванова",
  },
  {
    id: 2,
    name: "ПР-102",
    capacity: 23,
    grade: 1,
    supervisor: "Максим Петров",
  },
  {
    id: 3,
    name: "БС-201",
    capacity: 22,
    grade: 2,
    supervisor: "Анна Смирнова",
  },
  {
    id: 4,
    name: "БС-202",
    capacity: 24,
    grade: 2,
    supervisor: "Дмитрий Фролов",
  },
  {
    id: 5,
    name: "ПК-301",
    capacity: 20,
    grade: 3,
    supervisor: "Татьяна Васильева",
  },
  {
    id: 6,
    name: "ПК-302",
    capacity: 21,
    grade: 3,
    supervisor: "Сергей Морозов",
  },
  {
    id: 7,
    name: "АВ-401",
    capacity: 18,
    grade: 4,
    supervisor: "Елена Белова",
  },
  {
    id: 8,
    name: "АВ-402",
    capacity: 19,
    grade: 4,
    supervisor: "Александр Кузнецов",
  },
  {
    id: 9,
    name: "МК-501",
    capacity: 17,
    grade: 5,
    supervisor: "Юлия Тарасова",
  },
  {
    id: 10,
    name: "ПК-502",
    capacity: 20,
    grade: 5,
    supervisor: "Никита Орлов",
  },
];


export const lessonsData = [
  {
    id: 1,
    subject: "Проектная деятельность",
    class: "ПК-101",
    teacher: "Ольга Иванова",
  },
  {
    id: 2,
    subject: "Инженерная графика",
    class: "ПР-102",
    teacher: "Максим Петров",
  },
  {
    id: 3,
    subject: "Базы данных",
    class: "БС-201",
    teacher: "Анна Смирнова",
  },
  {
    id: 4,
    subject: "Архитектура компьютеров",
    class: "БС-202",
    teacher: "Дмитрий Фролов",
  },
  {
    id: 5,
    subject: "Программирование на Python",
    class: "ПК-301",
    teacher: "Татьяна Васильева",
  },
  {
    id: 6,
    subject: "Алгоритмы и структуры данных",
    class: "ПК-302",
    teacher: "Сергей Морозов",
  },
  {
    id: 7,
    subject: "Автоматизация технологических процессов",
    class: "АВ-401",
    teacher: "Елена Белова",
  },
  {
    id: 8,
    subject: "Проектирование интерфейсов",
    class: "АВ-402",
    teacher: "Александр Кузнецов",
  },
  {
    id: 9,
    subject: "Машинное обучение",
    class: "МК-501",
    teacher: "Юлия Тарасова",
  },
  {
    id: 10,
    subject: "Проектная практика",
    class: "ПК-502",
    teacher: "Никита Орлов",
  },
];


export const examsData = [
  {
    id: 1,
    subject: "Проектная деятельность",
    class: "ПК-101",
    teacher: "Ольга Иванова",
    date: "2025-06-01",
  },
  {
    id: 2,
    subject: "Инженерная графика",
    class: "ПР-102",
    teacher: "Максим Петров",
    date: "2025-06-02",
  },
  {
    id: 3,
    subject: "Базы данных",
    class: "БС-201",
    teacher: "Анна Смирнова",
    date: "2025-06-03",
  },
  {
    id: 4,
    subject: "Архитектура компьютеров",
    class: "БС-202",
    teacher: "Дмитрий Фролов",
    date: "2025-06-03",
  },
  {
    id: 5,
    subject: "Программирование на Python",
    class: "ПК-301",
    teacher: "Татьяна Васильева",
    date: "2025-06-04",
  },
  {
    id: 6,
    subject: "Алгоритмы и структуры данных",
    class: "ПК-302",
    teacher: "Сергей Морозов",
    date: "2025-06-04",
  },
  {
    id: 7,
    subject: "Автоматизация технологических процессов",
    class: "АВ-401",
    teacher: "Елена Белова",
    date: "2025-06-05",
  },
  {
    id: 8,
    subject: "Проектирование интерфейсов",
    class: "АВ-402",
    teacher: "Александр Кузнецов",
    date: "2025-06-05",
  },
  {
    id: 9,
    subject: "Машинное обучение",
    class: "МК-501",
    teacher: "Юлия Тарасова",
    date: "2025-06-06",
  },
  {
    id: 10,
    subject: "Проектная практика",
    class: "ПК-502",
    teacher: "Никита Орлов",
    date: "2025-06-06",
  },
];


export const assignmentsData = [
  {
    id: 1,
    subject: "Проектная деятельность",
    class: "ПК-101",
    teacher: "Ольга Иванова",
    dueDate: "2025-05-15",
  },
  {
    id: 2,
    subject: "Инженерная графика",
    class: "ПР-102",
    teacher: "Максим Петров",
    dueDate: "2025-05-16",
  },
  {
    id: 3,
    subject: "Базы данных",
    class: "БС-201",
    teacher: "Анна Смирнова",
    dueDate: "2025-05-17",
  },
  {
    id: 4,
    subject: "Архитектура компьютеров",
    class: "БС-202",
    teacher: "Дмитрий Фролов",
    dueDate: "2025-05-17",
  },
  {
    id: 5,
    subject: "Программирование на Python",
    class: "ПК-301",
    teacher: "Татьяна Васильева",
    dueDate: "2025-05-18",
  },
  {
    id: 6,
    subject: "Алгоритмы и структуры данных",
    class: "ПК-302",
    teacher: "Сергей Морозов",
    dueDate: "2025-05-18",
  },
  {
    id: 7,
    subject: "Автоматизация технологических процессов",
    class: "АВ-401",
    teacher: "Елена Белова",
    dueDate: "2025-05-19",
  },
  {
    id: 8,
    subject: "Проектирование интерфейсов",
    class: "АВ-402",
    teacher: "Александр Кузнецов",
    dueDate: "2025-05-19",
  },
  {
    id: 9,
    subject: "Машинное обучение",
    class: "МК-501",
    teacher: "Юлия Тарасова",
    dueDate: "2025-05-20",
  },
  {
    id: 10,
    subject: "Проектная практика",
    class: "ПК-502",
    teacher: "Никита Орлов",
    dueDate: "2025-05-20",
  },
];


export const resultsData = [
  {
    id: 1,
    subject: "Проектная деятельность",
    class: "ПК-101",
    teacher: "Ольга Иванова",
    student: "Алексей Смирнов",
    date: "2025-05-01",
    type: "exam",
    score: 88,
  },
  {
    id: 2,
    subject: "Инженерная графика",
    class: "ПР-102",
    teacher: "Максим Петров",
    student: "Екатерина Орлова",
    date: "2025-05-01",
    type: "exam",
    score: 92,
  },
  {
    id: 3,
    subject: "Базы данных",
    class: "БС-201",
    teacher: "Анна Смирнова",
    student: "Иван Кузьмин",
    date: "2025-05-01",
    type: "exam",
    score: 85,
  },
  {
    id: 4,
    subject: "Архитектура компьютеров",
    class: "БС-202",
    teacher: "Дмитрий Фролов",
    student: "Мария Никитина",
    date: "2025-05-01",
    type: "exam",
    score: 91,
  },
  {
    id: 5,
    subject: "Программирование на Python",
    class: "ПК-301",
    teacher: "Татьяна Васильева",
    student: "Денис Жуков",
    date: "2025-05-01",
    type: "exam",
    score: 95,
  },
  {
    id: 6,
    subject: "Алгоритмы и структуры данных",
    class: "ПК-302",
    teacher: "Сергей Морозов",
    student: "Светлана Алексеева",
    date: "2025-05-01",
    type: "exam",
    score: 87,
  },
  {
    id: 7,
    subject: "Автоматизация технологических процессов",
    class: "АВ-401",
    teacher: "Елена Белова",
    student: "Павел Романов",
    date: "2025-05-01",
    type: "exam",
    score: 89,
  },
  {
    id: 8,
    subject: "Проектирование интерфейсов",
    class: "АВ-402",
    teacher: "Александр Кузнецов",
    student: "Наталья Баранова",
    date: "2025-05-01",
    type: "exam",
    score: 93,
  },
  {
    id: 9,
    subject: "Машинное обучение",
    class: "МК-501",
    teacher: "Юлия Тарасова",
    student: "Артур Волков",
    date: "2025-05-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Проектная практика",
    class: "ПК-502",
    teacher: "Никита Орлов",
    student: "Вероника Попова",
    date: "2025-05-01",
    type: "exam",
    score: 94,
  },
];


export const eventsData = [
  {
    id: 1,
    title: "Хакатон: Разработка ИТ-решений",
    class: "ПК-101",
    date: "2025-04-15",
    startTime: "10:00",
    endTime: "18:00",
  },
  {
    id: 2,
    title: "Экскурсия в технопарк",
    class: "БС-102",
    date: "2025-04-16",
    startTime: "12:00",
    endTime: "15:00",
  },
  {
    id: 3,
    title: "День открытых дверей",
    class: "ПР-103",
    date: "2025-04-17",
    startTime: "09:00",
    endTime: "13:00",
  },
  {
    id: 4,
    title: "Тренинг по командной работе",
    class: "БС-104",
    date: "2025-04-18",
    startTime: "14:00",
    endTime: "17:00",
  },
  {
    id: 5,
    title: "Карьера в IT: встреча с выпускниками",
    class: "ПК-201",
    date: "2025-04-19",
    startTime: "11:00",
    endTime: "13:00",
  },
  {
    id: 6,
    title: "Выставка студенческих проектов",
    class: "МК-202",
    date: "2025-04-20",
    startTime: "10:00",
    endTime: "14:00",
  },
  {
    id: 7,
    title: "Фестиваль науки",
    class: "АВ-203",
    date: "2025-04-21",
    startTime: "10:00",
    endTime: "16:00",
  },
  {
    id: 8,
    title: "Кибертурнир по Dota 2",
    class: "ПК-204",
    date: "2025-04-22",
    startTime: "17:00",
    endTime: "21:00",
  },
  {
    id: 9,
    title: "Интерактивная лекция: Искусственный интеллект",
    class: "МК-301",
    date: "2025-04-23",
    startTime: "13:00",
    endTime: "15:00",
  },
  {
    id: 10,
    title: "День здоровья",
    class: "ПР-302",
    date: "2025-04-24",
    startTime: "10:00",
    endTime: "13:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "Изменение даты контрольной по математике",
    class: "ПК-101",
    date: "2025-04-10",
  },
  {
    id: 2,
    title: "Дополнительная лекция по дискретной математике",
    class: "БС-102",
    date: "2025-04-11",
  },
  {
    id: 3,
    title: "Сдача лабораторных по программированию",
    class: "ПР-103",
    date: "2025-04-12",
  },
  {
    id: 4,
    title: "Зачет по истории ИТ перенесён",
    class: "БС-104",
    date: "2025-04-13",
  },
  {
    id: 5,
    title: "Консультация по физике перед экзаменом",
    class: "ПК-201",
    date: "2025-04-14",
  },
  {
    id: 6,
    title: "Изменения в расписании экзаменационной сессии",
    class: "МК-202",
    date: "2025-04-15",
  },
  {
    id: 7,
    title: "Информация о курсовой работе",
    class: "АВ-203",
    date: "2025-04-16",
  },
  {
    id: 8,
    title: "Обязательная регистрация на факультатив",
    class: "ПК-204",
    date: "2025-04-17",
  },
  {
    id: 9,
    title: "Выдача допусков к экзаменам",
    class: "МК-301",
    date: "2025-04-18",
  },
  {
    id: 10,
    title: "Встреча с деканом факультета",
    class: "ПР-302",
    date: "2025-04-19",
  },
];


export const calendarEvents = [
  {
    title: "Проектная деятельность",
    allDay: false,
    start: new Date(2025, 4, 7, 9, 0),
    end: new Date(2025, 4, 7, 10, 30),
  },
  {
    title: "Промежуточная аттестация",
    allDay: false,
    start: new Date(2025, 4, 7, 13, 0),
    end: new Date(2025, 4, 7, 14, 30),
  },
  {
    title: "Английский язык",
    allDay: false,
    start: new Date(2025, 4, 7, 16, 30),
    end: new Date(2025, 4, 7, 18, 0),
  },
];

export const links = [
  {
    title: "МЕНЮ",
    list: [
      {
        title: "Главная",
        path: "/",
        icon: "/home.png",
        roles: ["admin", "teacher", "student"],
      },
      {
        title: "Преподаватели",
        path: "/list/teachers",
        icon: "/teacher.png",
        roles: ["admin"],
      },
      {
        title: "Студенты",
        path: "/list/students",
        icon: "/student.png",
        roles: ["admin", "teacher"],
      },
      {
        title: "Дисциплины",
        path: "/list/subjects",
        icon: "/subject.png",
        roles: ["admin"],
      },
      {
        title: "Аудитории",
        path: "/list/classes",
        icon: "/class.png",
        roles: ["admin", "teacher"],
      },
      {
        title: "Расписание",
        path: "/list/lessons",
        icon: "/lesson.png",
        roles: ["admin", "teacher"],
      },
      {
        title: "Экзамены",
        path: "/list/exams",
        icon: "/exam.png",
        roles: ["admin", "teacher", "student"],
      },
      {
        title: "Задания",
        path: "/list/assignments",
        icon: "/assignment.png",
        roles: ["admin", "teacher", "student"],
      },
      {
        title: "Успеваемость",
        path: "/list/results",
        icon: "/result.png",
        roles: ["admin", "teacher", "student"],
      },
      {
        title: "Посещаемость",
        path: "/list/attendance",
        icon: "/attendance.png",
        roles: ["admin", "teacher", "student"],
      },
      {
        title: "События",
        path: "/list/events",
        icon: "/calendar.png",
        roles: ["admin", "teacher", "student"],
      },
      {
        title: "Объявления",
        path: "/list/announcements",
        icon: "/announcement.png",
        roles: ["admin", "teacher", "student"],
      },
    ],
  },
  {
    title: "ОБОРУДОВАНИЕ",
    list: [
      {
        title: "Оборудование",
        path: "/list/equipment",
        icon: "/equipment.png",
        roles: ["admin", "teacher", "student"],
      },
      {
        title: "Бронирование",
        path: "/list/equipment/bookings",
        icon: "/equipmentBooking.png",
        roles: ["admin", "teacher", "student"],
      },
    ],
  },
  {
    title: "ПРОФИЛЬ",
    list: [
      {
        title: "Профиль",
        path: "/profile",
        icon: "/profile.png",
        roles: ["admin", "teacher", "student"],
      },
      {
        title: "Выход",
        path: "/logout",
        icon: "/logout.png",
        roles: ["admin", "teacher", "student"],
      },
    ],
  },
];
